# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Notifier:
        arguments:
            # Please be aware that order of channels is important (especially with 'first_working_channel' delivery policy)
            $notificationChannels:
                - '@App\Service\NotificationChannel\AmazonSES'
                - '@App\Service\NotificationChannel\Pushy'
                - '@App\Service\NotificationChannel\AlwaysBroken'
                - '@App\Service\NotificationChannel\DevNull'
                - '@App\Service\NotificationChannel\Twilio'

            # For available policies, check: \App\Enum\DeliveryPolicy
            $deliveryPolicy: 'all_channels'

    App\Repository\CustomerRepository:
        class: \App\Repository\CustomerDoctrineRepository

    App\Service\NotificationChannel\Pushy:
        arguments:
            $apiKey: '%env(resolve:PUSHY_API_KEY)%'

    App\Service\NotificationChannel\Twilio:
        arguments:
            $twilioNumber: '%env(resolve:TWILIO_NUMBER)%'

    Twilio\Rest\Client:
        arguments:
            $username: '%env(resolve:TWILIO_ACCOUNT_SID)%'
            $password: '%env(resolve:TWILIO_AUTH_TOKEN)%'

    App\Service\NotificationChannel\AmazonSES:
        arguments:
            $senderEmail: '%env(resolve:AWS_SES_SENDER_EMAIL)%'

    Aws\Ses\SesClient:
        arguments:
            - { region: '%env(resolve:AWS_REGION)%', profile: 'default', version: '2010-12-01' }
