# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Notifier:
        arguments:
            # Please be aware that order of channels is important (especially with 'first_working_channel' delivery policy)
            $notificationChannels:
                - '@App\Service\NotificationChannel\Pushy'
                - '@App\Service\NotificationChannel\AlwaysBroken'
                - '@App\Service\NotificationChannel\DevNull'
                - '@App\Service\NotificationChannel\AmazonSES'
                - '@App\Service\NotificationChannel\Twilio'

            # For available policies, check: \App\Enum\DeliveryPolicy
            $deliveryPolicy: 'all_channels'
